CREATE TABLE IF NOT EXISTS branches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) UNIQUE NOT NULL,
  name VARCHAR(120) NOT NULL,
  address VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('super_admin', 'branch_admin', 'staff')),
  branch_id INTEGER NULL REFERENCES branches(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS borrowers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cif_key VARCHAR(50) UNIQUE,
  branch_id INTEGER NULL REFERENCES branches(id) ON DELETE SET NULL,
  member_name VARCHAR(120),
  contact_info VARCHAR(80),
  address VARCHAR(255),
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(30),
  email VARCHAR(120),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  borrower_id INTEGER NOT NULL REFERENCES borrowers(id),
  loan_account_no VARCHAR(60) UNIQUE,
  loan_type VARCHAR(80),
  date_release DATE,
  maturity_date DATE,
  loan_amount NUMERIC(12, 2),
  principal_due NUMERIC(12, 2),
  penalty_due NUMERIC(12, 2),
  other_charges NUMERIC(12, 2) DEFAULT 0,
  par_age INTEGER DEFAULT 0,
  notes TEXT,
  principal NUMERIC(12, 2) NOT NULL,
  interest NUMERIC(12, 2) NOT NULL,
  penalty NUMERIC(12, 2) DEFAULT 0,
  due_date DATE NOT NULL,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'closed', 'overdue')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS collections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id INTEGER NOT NULL REFERENCES loans(id),
  amount NUMERIC(12, 2) NOT NULL,
  or_no VARCHAR(80),
  collected_at TIMESTAMP NOT NULL,
  created_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS loan_remarks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id INTEGER NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
  remark_text TEXT NOT NULL,
  remark_category VARCHAR(64) NOT NULL DEFAULT 'follow_up_collection',
  created_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS borrower_remarks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  borrower_id INTEGER NOT NULL REFERENCES borrowers(id) ON DELETE CASCADE,
  remark_text TEXT NOT NULL,
  remark_category VARCHAR(64) NOT NULL DEFAULT 'follow_up_collection',
  created_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO branches (id, code, name, address)
VALUES
  (1, 'MAIN', 'Main Branch', 'Head Office')
ON CONFLICT (id) DO UPDATE
SET code = EXCLUDED.code,
    name = EXCLUDED.name,
    address = EXCLUDED.address;

INSERT INTO users (username, password_hash, role, branch_id)
VALUES
  ('admin', '$2y$10$VVxFAof7KaaNJHcj4o6ij.nUjAmWwY8kaI.uYFgQaEqPGHeJwKH3C', 'super_admin', NULL),
  ('staff', '$2y$10$VVxFAof7KaaNJHcj4o6ij.nUjAmWwY8kaI.uYFgQaEqPGHeJwKH3C', 'staff', 1)
ON CONFLICT (username) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    branch_id = EXCLUDED.branch_id;

INSERT INTO borrowers (id, cif_key, member_name, contact_info, address, name, phone, email)
VALUES
  (1, 'CIF-0001', 'Ana Cruz', '09171234567', 'Manila City', 'Ana Cruz', '09171234567', 'ana@example.com'),
  (2, 'CIF-0002', 'Mark Lee', '09179876543', 'Quezon City', 'Mark Lee', '09179876543', 'mark@example.com')
ON CONFLICT (id) DO UPDATE
SET cif_key = EXCLUDED.cif_key,
    member_name = EXCLUDED.member_name,
    contact_info = EXCLUDED.contact_info,
    address = EXCLUDED.address,
    name = EXCLUDED.name,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email;

INSERT INTO loans (
  id,
  borrower_id,
  loan_account_no,
  loan_type,
  date_release,
  maturity_date,
  loan_amount,
  principal_due,
  penalty_due,
  other_charges,
  par_age,
  notes,
  principal,
  interest,
  penalty,
  due_date,
  status
)
VALUES
  (1, 1, 'LAN-0001', 'Salary Loan', '2025-09-15', '2026-02-15', 60000, 50000, 500, 250, 0, 'Initial account setup', 50000, 3000, 500, '2026-02-15', 'active'),
  (2, 2, 'LAN-0002', 'Business Loan', '2025-08-10', '2026-02-10', 85000, 75000, 900, 350, 9, 'Overdue for field follow-up', 75000, 4200, 900, '2026-02-10', 'overdue')
ON CONFLICT (id) DO UPDATE
SET borrower_id = EXCLUDED.borrower_id,
    loan_account_no = EXCLUDED.loan_account_no,
    loan_type = EXCLUDED.loan_type,
    date_release = EXCLUDED.date_release,
    maturity_date = EXCLUDED.maturity_date,
    loan_amount = EXCLUDED.loan_amount,
    principal_due = EXCLUDED.principal_due,
    penalty_due = EXCLUDED.penalty_due,
    other_charges = EXCLUDED.other_charges,
    par_age = EXCLUDED.par_age,
    notes = EXCLUDED.notes,
    principal = EXCLUDED.principal,
    interest = EXCLUDED.interest,
    penalty = EXCLUDED.penalty,
    due_date = EXCLUDED.due_date,
    status = EXCLUDED.status;

INSERT INTO collections (loan_id, amount, collected_at)
VALUES
  (1, 10000, CURRENT_TIMESTAMP),
  (2, 12000, CURRENT_TIMESTAMP);
